DROP DATABASE IF EXISTS LOGIN;

CREATE DATABASE LOGIN;

USE LOGIN;

CREATE TABLE USER (
    ID_USER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR (20),
    EMAIL VARCHAR(60),
    SENHA VARCHAR(255)
);